### ISSUE TITLE
file redirection error on ctrl+C

### ISSUE THREAD

**Issue by neofutur** [progrium/wssh#1]
hi i m using wssh to dump data to a file :

$ wssh websocket.mtgox.com:80/mtgox >depth.txt
 when i do a ctrl+c I get this strange error :
^C
Exception KeyError: KeyError(408721060,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

 nothing important, its still working, nbut i m wanted to give you the information ;)

( and many thanks for this great tool, much better than telnet or netcat for websockets ! )

**Comment by progrium** [comment]
Thanks!

**Comment by neofutur** [comment]
also, I have it working on gentoo / python 2.7, but wanted to ask you if it should work on python 2.6.

 not sure its related to python version, but on debian/python 2.6 i get : 

$ wssh http://websocket.mtgox.com:80/mtgox | grep depth >  d1.txt

Traceback (most recent call last):
  File "/bin/wssh", line 9, in <module>   load_entry_point('wssh==0.1.0', 'console_scripts', 'wssh')()
  File "/pythoninstall/lib/python2.6/site-packages/wssh-0.1.0-py2.6.egg/wssh/**init**.py", line 18, in main
    url = "ws://{}".format(url)
 ValueError: zero length field name in format

**Comment by neofutur** [comment]
another strange error after updating debian to unstable and python 2.7 : 

$ wssh http://websocket.mtgox.com:80/mtgox  > ~/tmp/d.txt
 Traceback (most recent call last):
 File "/usr/local/bin/wssh", line 9, in <module>
 load_entry_point('wssh==0.1.0', 'console_scripts', 'wssh')()
 File "/usr/local/lib/python2.7/dist-packages/wssh-0.1.0-py2.7.egg/wssh/**init**.py", line 24, in main
  client.connect(url.hostname, url.port, url.path)
 File "/usr/lib/python2.7/urlparse.py", line 107, in port
 return int(port, 10)

ValueError: invalid literal for int() with base 10: ''

EDIT : oups, forget this one,its the http:// that is causing a problem to the urlparse ( but it could be cool to remove the http:// before parsing if the user added it

**Comment by neofutur** [comment]
the http:// part can also be useful  for wss ( using https:// ) url, wssh wont work with https://socketio.nekoo.com/socket.io/socket.io.js

EDIT : hum forget it, this one is a socket.io websocket , and wssh is probably not handling the socket.io handshake ( this could be a feature request ;) , see http://socket.io/
