### ISSUE TITLE
ImportError: cannot import name UpgradableWSGIHandler

### ISSUE THREAD

**Issue by nairboon** [progrium/wssh#17]
after installing on ubuntu 12.10 i get this when running wssh:

```
Traceback (most recent call last):
 File "/usr/local/bin/wssh", line 9, in <module>
load_entry_point('wssh==0.1.0', 'console_scripts', 'wssh')()
 File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
 File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2311, in load_entry_point
return ep.load()
 File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2017, in load
entry = __import__(self.module_name, globals(),globals(), ['__name__'])
 File "/usr/local/lib/python2.7/dist-packages/wssh-0.1.0-py2.7.egg/wssh/__init__.py", line 9, in <module>
from . import server
 File "/usr/local/lib/python2.7/dist-packages/wssh-0.1.0-py2.7.egg/wssh/server.py", line 6, in <module>
from ws4py.server.geventserver import UpgradableWSGIHandler
  ImportError: cannot import name UpgradableWSGIHandler
```

**Comment by FooBarWidget** [comment]
This is because ws4py removed UpgradableWSGIHandler in 0.3.0-beta. Specifying 'ws4py==0.2.4' in setup.py solves this problem.

**Comment by joakime** [comment]
This problem also exists in Ubuntu 12.04, the same fix (specifying 'ws4py==0.2.4') works here as well.

**Comment by jefferai** [comment]
Unfortunately pypi no longer has ws4py 0.2.4 available. Manually installing ws4py 0.2.4 and removing that item from setup.py works, but I guess a more long-term fix is needed.

**Comment by progrium** [comment]
Perhaps pulling in that old class UpgradeableWSGIHandler into wssh...

On Tue, May 28, 2013 at 7:35 AM, Jeff Mitchell notifications@github.comwrote:

> Unfortunately pypi no longer has ws4py 0.2.4 available. Manually
> installing ws4py 0.2.4 and removing that item from setup.py works, but I
> guess a more long-term fix is needed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/progrium/wssh/issues/17#issuecomment-18554404
> .

## 

Jeff Lindsay
http://progrium.com
