### ISSUE TITLE
restarting on connection reset by peer

### ISSUE THREAD

**Issue by neofutur** [progrium/wssh#2]
if you have a network problem wssh with stop / crash on :

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent-0.13.6-py2.7-linux-i686.egg/gevent/greenlet.py", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/ws4py-0.2.1-py2.7.egg/ws4py/websocket.py", line 229, in run
    bytes = sock.recv(self.reading_buffer_size)
  File "/usr/lib/python2.7/site-packages/gevent-0.13.6-py2.7-linux-i686.egg/gevent/socket.py", line 418, in recv
return sock.recv(*args)
error: [Errno 104] Connection reset by peer
<Greenlet at 0x146bd07c: <bound method WebSocketClient.run of <ws4py.client.geventclient.WebSocketClient object at 0x147073cc>>> failed with error
```

 it could be a good feature to intercept the exception and restart / reconnect the websocket in this case

**Comment by progrium** [comment]
Yep, good call.
